FROM php:8-apache

# RUN apk update

# RUN apk add --no-cache bash

SHELL ["/bin/bash", "-c"]
RUN docker-php-ext-install -j$(nproc) mysqli
COPY app.conf /etc/apache2/conf-available/app.conf

RUN a2enconf app

# RUN echo "Include /usr/local/apache2/conf/app.conf" \
#     >> /usr/local/apache2/conf/httpd.conf \
#     && echo "Include /usr/local/apache2/conf/httpd.conf" \
#     >> /etc/apache2/apache2.conf
# 
# COPY demo.apache.conf /usr/local/apache2/conf/demo.apache.conf
# 
# RUN echo "Include /usr/local/apache2/conf/app.conf" \
#     >> /usr/local/apache2/conf/httpd.conf

COPY php.ini /usr/local/etc/php/
COPY ./src /src
RUN mkdir /app
RUN /bin/bash -c "/src/install /app"

EXPOSE 80