#!/bin/sh

if [ $# -eq 0 ]
  then
    echo "help: ./test [PATH (relativa o assoluta) della cartella public_html]"
else
    views_dir=$(echo $(pwd)/src/views)
    css_dir=$(echo $(pwd)/src/styles/css)
    img_dir=$(echo $(pwd)/imgs)
    js_dir=$(echo $(pwd)/style/js)
    public_path=$1
    
    rm -rf $public_path/*
    cd $public_path
    for file in `ls $views_dir`; do
	ln -s $views_dir/$file
    done
    ln -s $css_dir css
    ln -s $img_dir imgs
    ln -s $js_dir js
    rm -f template;
    rm -f home_statica.html;
fi
