#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if [ $# -eq 0 ]
  then
    echo "help: ./install [PATH (relativa o assoluta) della cartella public_html]"
else
    views_dir=$DIR/views
    css_dir=$DIR/styles/css/
    img_dir=$DIR/imgs/
    js_dir=$DIR/styles/js/
    public_path=$1
    
    rm -rf $public_path/*
    rm -rf $public_path/.htaccess
    cd $public_path
    for file in `ls $views_dir`; do
	ln -s $views_dir/$file
    done
    ln -s $css_dir css
    ln -s $img_dir imgs
    ln -s $js_dir js
    rm -f template;
fi
